apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobeinabox-deployment
  labels:
    app: jobeinabox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobeinabox
  template:
    metadata:
      labels:
        app: jobeinabox
    spec:
      containers:
      - name: jobeinabox-container
        image: etutorplusplus/jobeinabox:20230829
        env:
        - name: SIM_JOBE_JOBS
          value: "16"
          
---

apiVersion: v1
kind: Service
metadata:
  name: jobeinabox-service
spec:
  type: NodePort
  selector:
    app: jobeinabox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
